# kubectl create -f prod-definition.yml

apiversion: v1 # tum tanimlama dokumanlarinda en basta olur
kind: Pod

metadata:
  name: myapp-pord
  labels:
    app: my-app
    type: front-end # tag

spec:
  containers:
    - name: nginx-container
      image: nginx
      prorts:
        - containerPort:80
      envFrom: # env variables
        - configMapRef: 
          name: app-config # name in config map. injected config example 
          