# kubectl create -f persistent-volume-claim-definition.yaml

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: persistent-volume-claim

spec:
  accessModes:
    - ReadWriteOnce
  
  resources:
    requests:
      storage: 500mi
